#! /usr/bin/env ruby
require '../syntax'

line = 'hello here is a test line */ will do';
VdtsComment.line=line;
if VdtsComment.isMultiComment?
	puts "detect multiComment";
else
	puts "not detect multiComment";
end

puts VdtsComment.willowed;
