#! /usr/bin/env ruby

require 'rhload';
$LOAD_PATH << File.dirname(File.absolute_path(__FILE__));

rhload 'lib/exceptions.rb';
rhload 'lib/mainentry.rb';

$projectRoot  = ENV['PROJECT_ROOT'];
$outAnchor    = ENV['OUT_ANCHOR'] || './out';
$projectEntry = ENV['SIMF_ENTRY'];
$topContext   = ENV['SIMF_CONTEXT'];

begin
	raise EnvException.new(", no PROJECT_ROOT specified") if not $projectRoot;
	raise EnvException.new(", no SIMF_ENTRY specified") if not $projectEntry;
	raise EnvException.new(", no SIMF_CONTEXT specified") if not $topContext;
rescue EnvException => e
	e.process("project setup fatal");
end

$projectRoot = File.absolute_path($projectRoot);
e = MainEntry.new($projectRoot,$projectEntry,$topContext);
## TODO, will add exception process here
$SIG = e.run();
puts "program exists with sig: #{$SIG}";
exit $SIG;
