#! /usr/bin/env ruby

def init() ##{{{
	libpath = File.dirname(File.absolute_path(__FILE__));
	$LOAD_PATH << libpath;
	# require the core of the tool
	require 'Rsim.rb';
end ##}}}
def main() ##{{{
	init();
	signal = Rsim.start();
	return signal;
end ##}}}

exit main();

