#! /usr/bin/env python3


import os;
import sys;

thisDir = os.path.dirname(__file__);
includeDir = thisDir+'/include';
sys.path.append(includeDir);
sys.path.append(thisDir);


from const import const;
from runfConfig import runfConfig;
import runfSys;

def constDefinition(): ## {
	const.errorFilelistNotSpecified = 1;
	const.errorFileNotExists = 2;
	const.errorWorkDirNotSpecified = 3;
	const.normalExitSignal = 0;

## }

def preLoads(): ## {
	constDefinition();
## }

def main(): ## {
	preLoads();

	localSig = 0;

	cfgH = runfConfig();
	localSig = cfgH.parseArgsAndProcessToolConfigs();
	if localSig: return localSig;

	if cfgH.needBuild(): ## {
		import flows.buildFlow as bf;
		bf.preBuild();
		bf.build(cfgH);
		bf.postBuild();
		## TODO
	## }
	if cfgH.needElab():
		## TODO
	if cfgH.needRun():
		## TODO


	return localSig;
## }






SIG = main();
runfSys.exit(SIG);
