#! /usr/bin/env ruby


$LOAD_PATH << File.dirname(__FILE__)+'/lib';

require "config";
require "analyzer";
require "publisher";

def main ##{
	localSig = 0;

	config = ProgramConfig.new();
	analyzer = VdtsAnalyzer.new(config);
	publisher = VerilogPublisher.new(analyzer);


	config.parseUserOptions;
	analyzer.analyzeSrc;
##	publisher.publish;

	return localSig;
end ##}



$SIG = main;
exit($SIG);
